AC_DEFUN([AM_PATH_LIBGLADE_2_0], [
	AC_PATH_PROG(PKG_CONFIG, pkg-config, no)
	LIBGLADE_CFLAGS=`$PKG_CONFIG --cflags libglade-2.0`
	LIBGLADE_LIBS=`$PKG_CONFIG --libs libglade-2.0`
	AC_SUBST(LIBGLADE_CFLAGS)
	AC_SUBST(LIBGLADE_LIBS)
])
