.TH plot-entropy "1" "19 November 2006" "rdd 2.0"
.SH NAME
plot-entropy \- part of the rdd toolkit 
.SH SYNOPSIS
.B plot-entropy <\fIOPTION\fR> infile [lo hi]

.SH DESCRIPTION
.\" Add any additional description here
.PP

.SH OPTIONS
.TP
\fB\-o \fR
output file.

.TP
\fB\-t \fR
title.

.TP
\fB\-b \fR
block size.

.TP
\fB\-x \fR
exclude file.


.SH BUG REPORTS
Report bugs to <rdd@holmes.nl>.
.SH ACKNOWLEDGEMENTS
Many thanks to all who reported bugs and successes, and who
suggested improvements.
You know who you are.
.SH COPYRIGHT
Copyright \(co 2002-2003 Netherlands Forensic Institute
.br
This software comes with NO warranty;
not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
