.TH rddi "1" "19 November 2006" "rdd 2.0"
.SH NAME
rddi \- interactive shell, part of the rdd toolkit 
.SH SYNOPSIS
.B rddi 

.SH DESCRIPTION
.PP
This is the rdd command-line wizard.  It will help you construct a
sensible rdd command line.  The wizard will ask a series of questions
and will eventually print a command line that is based on your answers.
Optionally, the wizard will also run this command.
.PP

.SH OPTIONS
No arguments can be given

.SH BUG REPORTS
Report bugs to <rdd@holmes.nl>.
.SH ACKNOWLEDGEMENTS
Many thanks to all who reported bugs and successes, and who
suggested improvements.
You know who you are.
.SH COPYRIGHT
Copyright \(co 2002-2003 Netherlands Forensic Institute
.br
This software comes with NO warranty;
not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
